repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0  # CURRENT_TAG/COMMIT_HASH
    hooks:
    -   id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell --skip="*.js,*.html,*.css, *.svg" --ignore-words=.codespell-ignore.txt
        language: python
        types: [text]

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
    -   id: markdownlint
        args:
          [
            "--disable=MD013",
            "--disable=MD047"
          ]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.1
    hooks:
    -   id: nbqa-black
        name: nbqa-black
        description: "Run 'black' on a Jupyter Notebook"
        entry: nbqa black
        language: python
        require_serial: true
        types: [jupyter]
        additional_dependencies: [black]